server:
  port: 7088

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3397/microservices?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 6969
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # <- DB entries auto update
    show-sql: true       # <- SQL true
    
    
eureka:
    instance:
      prefer-ip-address: true
    client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
      defaultZone: http://localhost:8761/eureka
  

