server:
  port: 7052

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3397/microservices?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 6969
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  config:
    import: optional:configserver:http://localhost:7054  # [optional] To get rid from application fallback.
      

  jpa:
    hibernate:
      ddl-auto: update   # <- DB entries auto update
    show-sql: true       # <- SQL true 
 # profiles:
  #  active: prod

